kind: ConfigMap
apiVersion: v1
metadata:
  name: consul-dr-cm
  namespace: consul-service
  annotations:
    switchoverRetry: ""
data:
  mode: active
  noWait: 'false'
  status_comment: ""
  status_mode: active
  status_status: done
